Update patch set 2
Patch Set 2:

> Patch Set 2:
> 
> > Patch Set 2: Verified-1 Code-Review-2
> > 
> > Compiling with errors:
> 
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_main.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_scan_roam.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_dev_if.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_mgmt.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_power.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_data.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_utils.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wma_features.o
>   CC      drivers/staging/qcacld-3.0/core/wma/src/wlan_qct_wma_legacy.o
> ../../../../../../../out/18/kernel/sony/sdm845/drivers/staging/qcacld-3.0/core/w
> ma/src/wma_utils.c:4667:3: error: misleading indentation; statement is not part 
> of the previous 'if' [-Werror,-Wmisleading-indentation]
>                 mac_ctx = (tpAniSirGlobal)cds_get_context(QDF_MODULE_ID_PE);
>                 ^
> ../../../../../../../out/18/kernel/sony/sdm845/drivers/staging/qcacld-3.0/core/w
> ma/src/wma_utils.c:4660:2: note: previous statement is here
>         if (wma->bmiss_skip_full_scan)
>         ^
> 1 error generated.
> make[4]: *** [/home/sjll/out/18/kernel/sony/sdm845/scripts/Makefile.build:339: d
> rivers/staging/qcacld-3.0/core/wma/src/wma_utils.o] Error 1
> make[4]: *** Waiting for unfinished jobs....
> make[3]: *** [/home/sjll/out/18/kernel/sony/sdm845/scripts/Makefile.build:653: d
> rivers/staging/qcacld-3.0] Error 2
> make[2]: *** [/home/sjll/out/18/kernel/sony/sdm845/scripts/Makefile.build:653: d
> rivers/staging] Error 2
> make[1]: *** [/home/sjll/out/18/kernel/sony/sdm845/Makefile:1136: drivers] Error
>  2
> make[1]: Leaving directory '/home/sjll/realout/18/target/product/akatsuki/obj/KE
> RNEL_OBJ'
> make: *** [Makefile:152: sub-make] Error 2
> make: Leaving directory '/home/sjll/out/18/kernel/sony/sdm845'
> 08:19:26 ninja failed with: exit status 1

Hi, I test build and flashing it for my XZ2. And sorry for not being specific. This commit depends on https://review.lineageos.org/c/LineageOS/android_kernel_sony_sdm845/+/313895

Patch-set: 2